language: smalltalk

#sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-7.0

script:
  - bin/fetch-configlet
  - bin/configlet lint --track-id pharo .
