name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
        runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@master

      - name: Configlet Linter
        run: configlet lint --track-id pharo .
    
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with: 
          smalltalk-version: 'Pharo64-8.0'
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
        
  tree:
    runs-on: ubuntu-latest
        runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@master

      - name: Configlet Tree
        run: configlet tree --with-difficulty .
